### ISSUE TITLE
Beschreibung der genauen Endpoints

### ISSUE THREAD

**Issue by Meschkov** [DrPhilippBillion/ONE-Record-Testbench#2]
Wie in der technischen Beschreibung zu sehen sind die einzelnen Test Teilnehmer auch tatsächlich eigene Server.
Wir brauchen also keine Endpunkte wie `/shipper/*` , `/carrier/*` als prefix in der Route. 
Laut unserer test Implementierung beginnt alles mit der Company wie z.B. bei dem Logistics Object:
<img width="377" alt="image" src="https://user-images.githubusercontent.com/13832616/160178157-ad918257-97b3-4257-b595-a57a60448115.png">

https://github.com/DrPhilippBillion/ONE-Record-Testbench/blob/03f1154b06753cf562d281baffa158b0681be298/UseCase%20definitions.md?plain=1#L11-L12

Hier wäre zu klären was die genauen Endpoints für Pieces sind und ob diese überhaupt fest vorgeschrieben oder frei wählbar sind.

**Comment by mskopp** [comment]
Ich stimme zu das wir das in unserem Scenario nicht "brauchen". Aber im Workshop haben wir gesehen das es diese `${licensePlate}` zumindest bei Beispielen gibt, zB. bei für die "Logistics Object ID" (IATA-1R-AS-API-Security-Specifications-vCOTB-Nov2020.pdf, Seite 8): https://{ORS Domain}/{license plate}/{unique id to identify LO}

Ich sehe auch nicht, dass ein Schema hier fest vorgeschrieben ist - nur die "uniqueness pro LO-ID" ist verlangt.
Aber man könnte argumentieren das es "good practice" wäre, wenn wir hier nahe an der Spezifikation bleiben und das es "good practice" wäre, mit den REST-Endpunkten auch analog zu den LO-IDs zu sein.

**Comment by DrPhilippBillion** [comment]
Alles richtig, beide Optionen machen Sinn. Für Plattformen, die auch als solche "in Erscheinung treten wollen", macht die `{ORS Domain}`-Lösung Sinn, für große Stakeholder macht eine eigene Domain Sinn. Zur Abdeckung aller Anforderungen würde ich beide Varianten in die UseCases aufnehmen.
